BTPATH=/home/sara/bullet3/bullet-build/src
all:
	g++ -std=c++11 -DBT_USE_DOUBLE_PRECISION short_chain.cpp -I /home/sara/bullet3/src $(BTPATH)/BulletDynamics/libBulletDynamics.a  $(BTPATH)/BulletCollision/libBulletCollision.a $(BTPATH)/LinearMath/libLinearMath.a constants.h
