all:
	g++ -std=c++11 -DBT_USE_DOUBLE_PRECISION short_chain.cpp -lGL -lGLU -I ../../bullet3/src ${BTPATH}/BulletDynamics/libBulletDynamics.a  ${BTPATH}/BulletCollision/libBulletCollision.a ${BTPATH}/LinearMath/libLinearMath.a
